---
title: "ggplot2 academic"
author: "王小二"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: flatly
    highlight: pygments
    code_download: true
    code_folding: show
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
---




用自己的数据画出云雨图，参考代码如下。

## 宏包

需要提前安装一些宏包
```{r, eval=FALSE}
install.packages(c("palmerpenguins", "see", "ggdist", "colorspace", "gghalves", "glue"))
```



## 数据
```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(palmerpenguins)
library(see)

penguins <- penguins %>% 
  drop_na()
```





## 图1

```{r, warning=FALSE, message=FALSE}
penguins %>% 
  ggplot(aes(x = species, y = bill_length_mm, fill = species)) +
  geom_violinhalf() +
  geom_dotplot(
    binaxis = "y", stackdir = "down",
    dotsize = .4, position = position_nudge(-0.025)
  ) +
  theme_modern() +
  stat_summary(
    fun.data = mean_sdl,
    fun.args = list(mult = 1),
    geom = "pointrange",
    position = position_nudge(0.05)
  ) +
  scale_fill_manual(values = c("#9fb69b", "#f7cfad", "#e8867c")) +
  labs(y = "bill length (mm)")
```




## 图2

```{r, warning=FALSE, message=FALSE}
my_pal <- rcartocolor::carto_pal(n = 8, name = "Bold")[c(1, 3, 7, 2)]


penguins %>% 
  ggplot(aes(x = species, y = bill_length_mm, color = species, fill = species)) +
  scale_y_continuous(breaks = 1:9) +
  scale_color_manual(values = my_pal, guide = "none") +
  scale_fill_manual(values = my_pal, guide = "none") + 
  
  geom_boxplot(
    width = .2, fill = "white",
    size = 1.5, outlier.shape = NA
  ) +
  ggdist::stat_halfeye(
    adjust = .33,  ## bandwidth
    width  = .67, 
    color  = NA,   ## remove slab interval
    position = position_nudge(x = .15)
  ) +
  gghalves::geom_half_point(
    side = "l", 
    range_scale = .3, 
    alpha = .5, size = 3
  )
```




## 图3

```{r, warning=FALSE, message=FALSE}
df_peng_stats <- 
  penguins %>% 
  mutate(bill_ratio = bill_length_mm / bill_depth_mm) %>% 
  group_by(species) %>% 
  mutate(
    n = n(),
    median = median(bill_ratio),
    max = max(bill_ratio)
  ) %>% 
  ungroup() %>% 
  mutate(species_num = as.numeric(fct_rev(species))) 


df_peng_stats %>% 
  ggplot(aes(bill_ratio, species_num, color = species)) +
  stat_summary(
    geom = "linerange",
    fun.min = function(x) -Inf,
    fun.max = function(x) median(x, na.rm = TRUE),
    linetype = "dotted",
    orientation = "y",
    size = .7
  ) +
  geom_point(
    aes(y = species_num - .15), 
    shape = "|",
    size = 5,
    alpha = .33
  ) +
  ggdist::stat_halfeye(
    aes(
      y = species_num,
      color = species,
      fill = after_scale(colorspace::lighten(color, .5))
    ),
    shape = 18,
    point_size = 3,
    interval_size = 1.8,
    adjust = .5,
    .width = c(0, 1)
  ) +
  geom_text(
    aes(x = median, label = format(round(median, 2), nsmall = 2)),
    stat = "unique",
    color = "white",
    family = "Open Sans",
    fontface = "bold",
    size = 3.4,
    nudge_y = .15
  ) +
  geom_text(
    aes(x = max, label = glue::glue("n = {n}")),
    stat = "unique",
    family = "Open Sans",
    fontface = "bold",
    size = 3.5,
    hjust = 0,
    nudge_x = .01,
    nudge_y = .02
  ) +
  coord_cartesian(clip = "off", expand = FALSE) +
  scale_x_continuous(
    limits = c(1.6, 3.8),
    breaks = seq(1.6, 3.8, by = .2)
  ) +
  scale_y_continuous(
    limits = c(.55, NA),
    breaks = 1:3,
    labels = c("Gentoo", "Chinstrap", "Adélie")
  ) +
  scale_color_manual(values = c("#3d6721", "#a86826", "#006c89"), guide = "none") +
  scale_fill_manual(values = c("#3d6721", "#a86826", "#006c89"), guide = "none") +
  labs(
    x = "Bill ratio",
    y = NULL,
    subtitle = "Raincloud plot shwoing the distribution of bill ratios, estimated as bill length divided by bill depth."
  ) +
  theme(
    panel.grid.major.x = element_line(size = .35),
    panel.grid.major.y = element_blank(),
    axis.text.y = element_text(size = 13),
    axis.ticks.length = unit(0, "lines"),
    plot.title.position = 'plot',
    plot.subtitle = element_text(margin = margin(t = 5, b = 10)),
    plot.margin = margin(10, 25, 10, 25)
  )
```


## 保存

你可能保存pdf格式，羡煞室友。

```{r, warning=FALSE, message=FALSE}
ggsave("raincloud_plot.pdf", width = 9, height = 5.2)
```

