---
title: "The beauty of layer()"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: flatly
    highlight: pygments
    code_download: true
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
---



# 题目

```{r}
library(tidyverse)
library(palmerpenguins)

penguins <- penguins %>% drop_na()
```


- 写出`stat_***()`版本
```{r}
ggplot(penguins, aes(x = species)) +
  geom_bar()

ggplot(penguins, aes(x = species)) +
  stat_count()
```


- 想想为什么图形都是一样的
```{r}
# count(penguins, species)

penguins %>% 
  ggplot(aes(x = species)) +
  geom_bar(stat = "count")


penguins %>% 
  count(species) %>%
  ggplot(aes(x = species, y = n)) +
  geom_bar(stat = "identity")


penguins %>% 
  count(species) %>%
  ggplot(aes(x = species, y = n)) +
  geom_col()
```

- 你会选择哪一种方法？

```{r}
penguins %>% 
  count(species) %>% 
  ggplot(aes(x = species, y = n)) +
  geom_col() +
  geom_text(aes(label = n), vjust = -0.4)


penguins %>%
  ggplot(aes(species)) +
  stat_count(geom = "bar") +
  stat_count(
    aes(label = after_stat(count)),
    geom = "text", vjust = -.4
  )  
```

- 比较下列图形的区别
```{r}
penguins %>% 
  ggplot(aes(y = species)) +
  geom_bar(aes(x = stat(count)))


penguins %>% 
  ggplot(aes(y = species)) +
  geom_bar(aes(x = stat(count) / sum(stat(count)))) +
  scale_x_continuous(labels = scales::percent)


penguins %>% 
  ggplot(aes(y = species)) +
  geom_bar(aes(x = stat(count) / sum(count))) +
  scale_x_continuous(labels = scales::percent)
```



- 写出下图的`geom_***()`版本和`stat_***()`
```{r}
ggplot() +
  layer(
      data       = penguins,
      mapping    = aes(x = species, y = bill_length_mm, color = fct_rev(sex)),
      stat       = "summary", 
      params     = list(fun = "mean"),
      geom       = "point",
      position   = position_dodge(width = 0.5)
  )

```


```{r}
penguins %>% 
  ggplot(aes(x = species, y = bill_length_mm, color = fct_rev(sex))) +
  stat_summary(
    geom       = "point",
    fun        = mean,
    position   = position_dodge(width = 0.5)
  )


penguins %>% 
  ggplot(aes(x = species, y = bill_length_mm, color = fct_rev(sex))) +
  geom_point(
    stat       = "summary",
    fun        = mean,
    position   = position_dodge(width = 0.5)
  )
```



- 用`stat_summary()`重写下面的代码

```{r}
m <- penguins %>%
  group_by(sex) %>%
  summarise(
    mean = mean(body_mass_g)
  )
m


penguins %>%
  ggplot(aes(x = sex, y = body_mass_g)) +
  geom_jitter() +
  geom_point(
    data = m, aes(y = mean), size = 5, color = "red"
  ) +
  geom_text(
    data = m,
    aes(x = sex, y = mean, label = round(mean, 2)), size = 5,
    color = "red", vjust = -1
  )
```


```{r}
penguins %>%
  ggplot(aes(x = sex, y = body_mass_g)) +
  geom_jitter() +
  stat_summary(
    fun.data = mean_se,
    geom = "point",
    color = "red",
    size = 5
  ) +
  stat_summary(
    fun.data = mean_se,
    mapping = aes(label = round(after_stat(y), 2)),
    geom = "text",
    color = "red",
    size = 5,
    vjust = -1
  ) 
```


