---
title: "ggplot2之标度作业2"
author: "王小二"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: flatly
    highlight: pygments
    code_download: true
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
---




# 作业

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(palmerpenguins)
penguins <- penguins %>% drop_na()

penguins
```



1. 改造以下代码，要求每组高于bill_depth_mm均值的，透明度为1，否则为0.3
```{r, message=FALSE, warning=FALSE}
penguins %>% 
  ggplot(aes(x = bill_length_mm, y = bill_depth_mm, color = species)) +
  geom_point(size = 5, show.legend = FALSE)
```


```{r, message=FALSE, warning=FALSE}
penguins %>% 
  group_by(species) %>% 
  mutate(cutpoint = if_else(bill_depth_mm >= mean(bill_depth_mm), "a", "b")) %>% 
  
  ggplot(aes(x = bill_length_mm, y = bill_depth_mm, color = species, alpha = cutpoint)) +
  geom_point(size = 5, show.legend = FALSE) +
  scale_alpha_manual(
    values = c("a" = 1, "b" = 0.3)
  )
```




2. 改造以下代码，要求低于每组bill_depth_mm均值的点，用灰色
```{r}
penguins %>% 
  ggplot(aes(x = bill_length_mm, y = bill_depth_mm, color = species)) +
  geom_point(size = 5, alpha = 0.7, show.legend = FALSE)
```


```{r, message=FALSE, warning=FALSE}
penguins %>% 
  group_by(species) %>% 
  mutate(maxpoint = if_else(bill_depth_mm > mean(bill_depth_mm), cur_group_id(), NA_integer_)) %>% 
  mutate(maxpoint = as.factor(maxpoint)) %>% 
  
  ggplot(aes(x = bill_length_mm, y = bill_depth_mm, color = maxpoint)) +
  geom_point(size = 5, alpha = 0.7, show.legend = FALSE) 
```




3. 改造下面代码，要求每组中bill_length_mm最长的那个点是实心点，其它的点是空心点
```{r, message=FALSE, warning=FALSE}
penguins %>% 
  ggplot(aes(x = bill_length_mm, y = bill_depth_mm, color = species)) +
  geom_point(shape = 21, size = 5, show.legend = FALSE)
```



```{r, message=FALSE, warning=FALSE}
penguins %>% 
  group_by(species) %>% 
  mutate(maxpoint = if_else(bill_length_mm == max(bill_length_mm), cur_group_id(), 0L)) %>% 
  mutate(maxpoint = as.factor(maxpoint)) %>% 
  
  ggplot(aes(x = bill_length_mm, y = bill_depth_mm, color = species)) +
  geom_point(aes(fill = maxpoint), 
    shape = 21, size = 5, show.legend = FALSE
  ) +
  scale_color_manual(
    breaks = c("Adelie", "Chinstrap", "Gentoo"), 
    values = c("red", "blue", "orange")
  ) +
  scale_fill_manual(
    values = c("0" = "white", "1" = "red", "2" = "blue", "3" = "orange")
  )
```



或者
```{r, message=FALSE, warning=FALSE}
penguins %>% 
  group_by(species) %>% 
  mutate(maxpoint = if_else(bill_length_mm == max(bill_length_mm), bill_length_mm, NA_real_)) %>% 

  ggplot(aes(x = bill_length_mm, y = bill_depth_mm, color = species)) +
  geom_point(shape = 21, size = 5) +
  geom_point(aes(x = maxpoint), size = 5) +
  geom_text(aes(label = maxpoint), size = 3, vjust = 2.5, color = "black") +
  theme(legend.position = "none")
```

