---
title: "dplyr作业"
author: "王小二"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: flatly
    highlight: pygments
    code_download: true
    code_folding: show
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
---



# 题目 1

判断成绩是否高于各科均值，是就1 否则0

```{r, message=FALSE, warning=FALSE}
library(tidyverse)

df <- tibble::tribble(
    ~name, ~chinese, ~engish, ~physics, ~sport, ~music,
   "Aice",       85,      56,       56,     54,     78,
    "Bob",       75,      78,       77,     56,     69,
   "Cake",       69,      41,       88,     89,     59,
   "Dave",       90,      66,       74,     82,     60,
    "Eve",       68,      85,       75,     69,     21,
    "Fod",       77,      74,       62,     74,     88,
  "Gimme",       56,      88,       75,     69,     34
  )
df
```


```{r}
df %>%
  mutate(
    across(-name, ~ if_else(.x > mean(.x), 1, 0))
  )
```


# 题目 2

希望数据框第2列到第6列的数值翻转，
具体为：1变成6, 2变成5，3变成4，4变成3，5变成2，6变成1

```{r}
df <- tibble::tribble(
  ~id, ~a_r, ~b_r, ~c_r, ~d_r, ~e_r,
  "a",    4,    4,    2,    5,    1,
  "b",    5,    4,    6,    2,    4,
  "c",    5,    3,    4,    1,    6,
  "d",    1,    1,    2,    5,    5,
  "e",    4,    3,    4,    5,    2,
  "f",    4,    3,    5,    5,    3,
  "g",    5,    4,    1,    1,    1
  )
df
```


```{r}
## 方法1
df %>%
  mutate(
    across(ends_with("_r"), ~ case_when(
      .x == 1 ~ 6,
      .x == 2 ~ 5,
      .x == 3 ~ 4,
      .x == 4 ~ 3,
      .x == 5 ~ 2,
      .x == 6 ~ 1
    ))
  )
```


```{r}
## 方法2

df %>%
  mutate(
    across(ends_with("_r"), ~ 7 - .x)
  )
```

