---
title: "《R语言数据分析》中期考核"
author: "王小二"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: flatly
    highlight: pygments
    code_download: true
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
---



# 中期考核要求

-   中期考核共`r 16 + 4`道题，后4道题属于选做题
-   在完成代码后，渲染生成html格式文档
-   以自己**学号**重命名html文档（注意是学号、不是姓名）
-   于2022年2月08日（周二）20:00前提交学习委员 `357119952@qq.com`



# 数据集

## 数据读入

作业使用的数据集来源于网站(<https://data.worldbank.org/country>)，它收集了不同洲(continent = 5)、不同国家(country = 215)历年(1961 - 2018)的**经济指标**

```{r, message=FALSE, warning=FALSE}
library(tidyverse)

world_bank_countries <- read_csv("data/world_bank_countries.csv")

glimpse(world_bank_countries)
```

## 数据变量

数据变量包括

| 变量名                        | 含义                         |
|:------------------------------|:-----------------------------|
| country                       | 国家                         |
| continent                     | 所在洲                       |
| year                          | 年份                         |
| access_to_electricity         | 通电比例                     |
| agricultural_land             | 农业用地比例                 |
| arable_land                   | 耕地比例                     |
| birth_rate                    | 出生率                       |
| co2_emissions_tons_per_capita | 人均二氧化碳排放量           |
| compulsory_education          | 义务教育时间                 |
| employers_of_total_population | 就业率                       |
| forest_land                   | 林地比例                     |
| gdp_per_capita                | 人均GDP                      |
| internet_usage                | 互联网普及率                 |
| life_expectancy_at_birth      | 预期寿命                     |
| mobile_cellular_subscriptions | 移动电话订阅率               |
| open_defecation               | 露天排便比例                 |
| basic_sanitation              | 基础卫生设施比例             |
| population_density            | 人口密度                     |
| population_male               | 男性占比                     |
| population_total              | 总人口                       |
| overweight                    | 体重超重比例                 |
| women_in_national_parliaments | 议会中女性人数占比           |
| female_to_male_labor_force    | 女性劳动力与男性的比例       |
| renewable_energie_consumption | 可再生能源在能源消费中的占比 |




# 题目

## 数据有多少条记录





## 数据包含多少个国家、多少年的记录





## 统计每个洲包含了多少个国家





## 统计每个变量缺失值的个数





## 2009年义务教育时间大于9年的国家占所有国家的比例





## 统计2008年每个洲寿命期望值的最小值、均值和最大值





## 2015年亚洲人口密度前五的国家





## 找出2001年每个洲出生率最低的国家






## 每个州，出生率波动最大的国家

提示，可计算出生率的标准差，函数为`sd()`，标准差越大，波动越大







## 画出德国寿命期望值的时间变化图







## 画出2017年人均GDP与出生率的散点图

要求不同的洲用不同的颜色






## 画出议会中女性人数占比的直方图

要求: 直方图的柱子边框色为"black"; 填充色为"steelblue"; 透明度为0.7






## 画出每个洲的各个国家寿命期望值随时间的变化图

要求: 用分面`facet_wrap(vars(continent), ncol = 5)`






## 画出2007年不同洲overweight分布的小提琴图

要求: 高亮亚洲





## 画出这四个国家(挪威、芬兰、丹麦、瑞典)可再生能源消耗占比的时间变化图






## 画出2016年这四个国家(西班牙、中国、俄罗斯和美国)人均二氧化碳排放量的柱状图

要求: 按照高度排序，并在柱子顶部添加具体数值






## 画出中国出生率的时间变化图，并在图中标出出生率最高的点





## 2014年人均GDP前20的国家，画出其耕地比例(arable_land)排名的柱状图

要求，先中心化耕地数值，并按照数值的正负赋不同的颜色





## 探索寿命期望值与人均GDP的关联





## 是不是越穷越爱生小孩

提示：可按人均GDP划分成五个等级，统计各等级下人均GDP的均值和出生率的均值，探索人均GDP与出生率的关联。

