---
title: "读写数据"
author: "王小二"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: flatly
    highlight: pygments
    code_download: true
    code_folding: hide
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
---


## 读写csv数据

```{r}
library(readr)

wages <- read_csv("./demo_data/wages.csv")
wages
```


```{r}
write_csv(wages, "wages_new.csv")
```



## 读写excel数据

```{r}
library(readxl)
olympics <- read_excel("./demo_data/olympics.xlsx")
olympics
```



```{r}
library(openxlsx)
write.xlsx(olympics, "olympics_new.xlsx")
```



## 读取rds数据

使用`readr::read_rds()`或者`readRDS()`

```{r}
kidiq <- readRDS("./demo_data/kidiq.RDS")
kidiq
```


```{r}
kidiq <- readr::read_rds("./demo_data/kidiq.RDS")
kidiq
```


```{r}
readr::write_rds(kidiq, "kidiq_new.rds")
```




## 读取 SPSS 数据

```{r}
library(haven)

survey <- read_sav("./demo_data/survey.sav")
survey
```



```{r}
write_sav(survey, "survey_new.sav")
```



## 更多格式

- `readr::read_tsv()`   制表符分隔的文件
- `readr::read_delim()` 指定分割符的文件
- `readr::read_fwf()`   固定宽度的文件
- `readr::read_table()` 空格分割的文件

