---
title: "ggplot2之标度作业2"
author: "王小二"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: flatly
    highlight: pygments
    code_download: true
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
---




# 作业

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(palmerpenguins)
penguins <- penguins %>% drop_na()

penguins
```


0. 改造以下代码，让bill_depth_mm值高于整体均值的点用红色，否则用灰色

```{r}
penguins %>% 
  ggplot(aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point(size = 3)
```


对于这种需求，我们一般采用**（分组、映射、标度）**三步走

- 分组。新增一列，对每只企鹅给一个标记，类似于sex这种分组变量

```{r}
penguins %>% 
  mutate(g = if_else(bill_length_mm > mean(bill_length_mm), "a", "b"))
```



- 映射。将新增的变量，映射给颜色，即"a"对应一种颜色，"b"对应另一种颜色

```{r}
penguins %>% 
  mutate(g = if_else(bill_length_mm > mean(bill_length_mm), "a", "b")) %>% 

  ggplot(aes(x = bill_length_mm, y = bill_depth_mm, color = g)) +
  geom_point(size = 3)
```



- 标度。修改颜色，让 "a" 对应红色， "b" 对应灰色 

```{r}
penguins %>% 
  mutate(g = if_else(bill_length_mm > mean(bill_length_mm), "a", "b")) %>% 
  ggplot(aes(x = bill_length_mm, y = bill_depth_mm, color = g)) +
  geom_point(size = 3) +
  
  scale_color_manual(
    values = c("a" = "red", "b" = "gray80")
  )
```



## 开始吧


1. 改造以下代码，要求每组高于bill_depth_mm均值的，透明度为1，否则为0.3
```{r, message=FALSE, warning=FALSE}
penguins %>% 
  ggplot(aes(x = bill_length_mm, y = bill_depth_mm, color = species)) +
  geom_point(size = 5, show.legend = FALSE)
```




2. 改造以下代码，要求低于每组bill_depth_mm均值的点，用灰色
```{r}
penguins %>% 
  ggplot(aes(x = bill_length_mm, y = bill_depth_mm, color = species)) +
  geom_point(size = 5, alpha = 0.7, show.legend = FALSE)
```





3. 改造下面代码，要求每组中bill_length_mm最长的那个点是实心点，其它的点是空心点
```{r, message=FALSE, warning=FALSE}
penguins %>% 
  ggplot(aes(x = bill_length_mm, y = bill_depth_mm, color = species)) +
  geom_point(shape = 21, size = 5, show.legend = FALSE)
```




